### PR TITLE
fix: harden trusted-proxies-count config parsing to prevent server errors

### LINKED ISSUE #2: Improper trusted-proxies-count Configuration Causes IP Authenticator Server Error
### Summary

The IP-based authenticator fails with a server-side exception if the `trusted-proxies-count` configuration value is missing, empty, or non-numeric. This can break the authentication flow (500 error) instead of failing safely with a user-visible error.

### Affected code

- `src/main/java/org/n52/keycloak/authentication/IPUserAuthenticatorConfig.java`
- `src/main/java/org/n52/keycloak/authentication/IPAddressHelper.java`

### Steps to reproduce

1. Configure the **IP Authenticator** in the admin console and enable `use-forwarded-header`.
2. Set **Number of trusted proxies** to an invalid value, for example:
   - Leave it empty, or
   - Set it to a non-numeric string like `"abc"`, or
   - (Depending on expectations) set it to `0`.
3. Trigger a login flow that uses this authenticator, with an `X-Forwarded-For` header present.

### Expected behavior

- Misconfiguration should be handled gracefully:
  - Invalid / missing `trusted-proxies-count` should either:
    - Fall back to a safe default, or
    - Cause a clear configuration error and return a proper challenge to the user (or a logged admin-facing warning),
  - No unhandled exceptions should bubble up to the client.

### Actual behavior

- `IPUserAuthenticatorConfig` calls:

  ```java
  this.trustedProxiesCount = Integer.parseInt(configMap.get(CONF_TRUSTED_PROXIES_COUNT));

### PR DESCRIPTION
**Pull request by ajinkyap9**
## Description

This PR hardens the parsing of the `trusted-proxies-count` configuration in the IP authenticator to prevent server-side failures caused by misconfiguration.

### What was fixed

- Previously, the authenticator could throw a server-side exception (HTTP 500) when `trusted-proxies-count` was missing, empty, or non-numeric.
- The configuration value is now parsed safely:
  - If the value is missing, empty, non-numeric, or less than `1`, a safe default of `1` is applied.
  - Invalid configurations are handled gracefully and no longer cause unhandled exceptions.
  - Clear warning messages are logged to inform administrators about invalid configuration values.
- This ensures the authentication flow remains stable and fails safely under misconfiguration.

Fixes #2

### CODE REVIEW

File: src/main/java/org/n52/keycloak/authentication/IPUserAuthenticatorConfig.java [hunk 1]
```diff
@@ -19,7 +25,30 @@ public class IPUserAuthenticatorConfig {
...
+            int count = Integer.parseInt(trustedProxiesCountStr.trim());
+            
+            if (count < 1) {
+                LOG.warn("Configuration value for 'trusted-proxies-count' must be >= 1. Got: " + count + ". Using default value: " + DEFAULT_TRUSTED_PROXIES_COUNT);
+                return DEFAULT_TRUSTED_PROXIES_COUNT;
+            }
+            
+            return count;
+        } catch (NumberFormatException e) {
+            LOG.warn("Configuration value for 'trusted-proxies-count' is not a valid integer: '" + trustedProxiesCountStr + "'. Using default value: " + DEFAULT_TRUSTED_PROXIES_COUNT, e);
```
Comment (SebaDro) [inline src/main/java/org/n52/keycloak/authentication/IPUserAuthenticatorConfig.java]: I think passing the exception to the log message at warn level is not necessary here. I'd suggest to remove it from the warn message. Instead, you could consider logging it at level TRACE.

**Review by SebaDro — CHANGES_REQUESTED** [review]
Hey @ajinkyap9. Thanks for the pull request. Just a small refinement regarding logging required but then I'm fine with it. If you could adress it, I will immediately merge it.

File: src/main/java/org/n52/keycloak/authentication/IPUserAuthenticatorConfig.java (hunk 1 above)
Comment (ajinkyap9) [reply src/main/java/org/n52/keycloak/authentication/IPUserAuthenticatorConfig.java]: the exception is no longer included at WARN level and is now logged at TRACE level

**Comment by ajinkyap9** [comment]
@SebaDro Changes made as per your suggestion, You can review it

**Review by SebaDro — APPROVED** [review]

**Comment by SebaDro** [comment]
Thanks for your revision. Looks good to me, now.
